name: Run E2E Tests

on:
  pull_request:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql:latest
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: ${{ secrets.POSTGRESQL_USERNAME }}
          POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
          POSTGRESQL_DATABASE: ${{ secrets.POSTGRESQL_DATABASE }}
        options: >-
          --health-cmd="pg_isready -U docker"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Wait for Postgres
        run: |
          for i in {1..10}; do
            nc -z localhost 5432 && break
            echo "Waiting for Postgres..."
            sleep 3
          done

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: postgresql://${{ secrets.POSTGRESQL_USERNAME }}:${{ secrets.POSTGRESQL_PASSWORD }}@localhost:5432/${{ secrets.POSTGRESQL_DATABASE }}?schema=public
