name: Run E2E Tests

on:
  pull_request:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql:latest
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: ${{ secrets.POSTGRESQL_USERNAME }}
          POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
          POSTGRESQL_DATABASE: ${{ secrets.POSTGRESQL_DATABASE }}
        options: >-
          --health-cmd="pg_isready -U docker"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Wait for Postgres
        run: |
          for i in {1..10}; do
            nc -z localhost 5432 && break
            echo "Waiting for Postgres..."
            sleep 3
          done

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          API_PORT: 3000
          DEV_PORT: 3007
          API_HOST: localhost
          NODE_ENV: development
          DATABASE_CLIENT: postgresql
          DATABASE_PORT: 5432
          DATABASE_USER: user
          DATABASE_PASSWORD: password
          DATABASE_NAME: apisolid
          DATABASE_HOST: localhost
          DATABASE_URL_LOCAL: postgres://user:password@localhost:5432/apisolid
          DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
          JWT_SECRET: your_jwt_secret
